### ISSUE TITLE
Label different

### ISSUE THREAD

**Issue by ue71603** [openTdataCH/ojp-demo-app-src#10]
![image](https://user-images.githubusercontent.com/24227470/127122426-21fe132d-696f-41b9-8cd0-68e90a8b1e40.png)

Should be: Add XML Request

**Comment by vasile** [comment]
Deployed a new feature, please have a look @ue71603 
The popup has 2 sections now - in the first you can paste custom TripRequest XML and that will be used to do a TripRequest call. Also(as before) you can paste custom TripRequest Response and visualize it immediately. 

![2021-07-input-xml-feature](https://user-images.githubusercontent.com/113994/127558448-8791765b-ed48-4329-b30a-889d8df38319.gif)
