### ISSUE TITLE
NumberOfResults for LIR and TR

### ISSUE THREAD

**Issue by AndreasAtSBB** [openTdataCH/ojp-demo-app-src#100]
We made a ticket for Mentz because in some cases relevant stops were not shown in **LIR** the result list.
Solution proposed from Mnetz is that we need to pass the LIR with the restrictions as follows:
                <ojp:Restrictions>
                    <ojp:Type>stop</ojp:Type>
                    <ojp:NumberOfResults>10</ojp:NumberOfResults>
                </ojp:Restrictions>
Please use this always for the **LIR** within the serch "From" and "To" entry field.

For the **TR** the numbers should be for all passive systems, for monomodal PT and all multimodal trips (Start, end, start&end):
<ojp:NumberOfResults>5</ojp:NumberOfResults>

All other monomodal options (Walking, Own car, Own bike, Bicycle-, eScooter-, Car-Sharing):
<ojp:NumberOfResults>1</ojp:NumberOfResults> 

For the active system "LA Beta" all multimodal options could be disabled for now. We just ask for PT trips in **TR**, since this is what every LinkingAlp partner system does support. And number should always be 3 then:
<ojp:NumberOfResults>3</ojp:NumberOfResults>

**Comment by vasile** [comment]
Fixed via #108
