### ISSUE TITLE
monomodal routing "Walking"

### ISSUE THREAD

**Issue by u233336** [openTdataCH/ojp-demo-app-src#101]
for a TripRequest with MOT "walk" we use an extension:

            <ojp:Origin>
              <ojp:MinDuration>PT2M</ojp:MinDuration>
              <ojp:MaxDuration>PT30M</ojp:MaxDuration>
              <ojp:MinDistance>100</ojp:MinDistance>
              <ojp:MaxDistance>20000</ojp:MaxDistance>
              <ojp:Mode>walk</ojp:Mode>
            </ojp:Origin>

Mentz is telling us, that we shouldn't use the extension but the IndividualTransportOptions in the origin:

          <ojp:IndividualTransportOptions>
            <ojp:Mode>walk</ojp:Mode>
            <ojp:MaxDistance>20000</ojp:MaxDistance>
            <ojp:MaxDuration>PT30M</ojp:MaxDuration>
            <ojp:MinDistance>100</ojp:MinDistance>
            <ojp:MinDuration>PT2M</ojp:MinDuration>
          </ojp:IndividualTransportOptions>

**Comment by u233336** [comment]
[TR_Walk.txt](https://github.com/openTdataCH/ojp-demo-app-src/files/11122637/TR_Walk.txt)
[TR_PTvsWalking.txt](https://github.com/openTdataCH/ojp-demo-app-src/files/11122638/TR_PTvsWalking.txt)

**Comment by vasile** [comment]
not relevany anymore
