### ISSUE TITLE
Trip declared as non-stop, despite more than on tripleg

### ISSUE THREAD

**Issue by AndreasAtSBB** [openTdataCH/ojp-demo-app-src#12]
If the trip is added by the "Debug Response XML" function, it happens that the trips are declared as non-stop, but there are stops.
(Not sure if that happens in a normal search).
See also the attached picture in the first line of text.
<img width="209" alt="Triplegs_as_nonstop" src="https://user-images.githubusercontent.com/85744651/127158418-217d8414-969b-40b4-8bb2-ff8421c8eb5f.png">

**Comment by vasile** [comment]
Thanks @AndreasAtSBB for reporting, can you also send me the actual TripRequest XML response that you are using? 

BTW, the popover changed a bit, you can now enter the response in the 2nd textarea box
![image](https://user-images.githubusercontent.com/113994/127630098-4610c406-0f03-45cd-9d21-178b02077fff.png)

**Comment by AndreasAtSBB** [comment]
Here is a valid Request:
<?xml version="1.0" encoding="utf-8"?>
<OJP xmlns="http://www.siri.org.uk/siri" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ojp="http://www.vdv.de/ojp" xsi:schemaLocation="http://www.siri.org.uk/siri ../ojp-xsd-v1.0/OJP.xsd" version="1.0">
	<OJPRequest>
		<ServiceRequest>
		     <RequestTimestamp>2021-03-25T10:48:48.556Z</RequestTimestamp>
			<RequestorRef>OJP_SDK_v1.0</RequestorRef>
			<ojp:OJPTripRequest>
				<RequestTimestamp>2021-03-25T10:48:48.556Z</RequestTimestamp>
				<ojp:Origin>
					<ojp:PlaceRef>
						<StopPointRef>8509798</StopPointRef>
						<ojp:LocationName>
                       			<ojp:Text>Müstair</ojp:Text>
                       		</ojp:LocationName>
					</ojp:PlaceRef>
					<ojp:DepArrTime>2021-07-14T14:38:22.976Z</ojp:DepArrTime>
				</ojp:Origin>
				<ojp:Destination>
					<ojp:PlaceRef>
						<StopPointRef>it:22021:2249</StopPointRef>
						<ojp:LocationName>
                       			<ojp:Text>Meran</ojp:Text>
                       		</ojp:LocationName>
					</ojp:PlaceRef>
				</ojp:Destination>
				<ojp:Params>
					<ojp:NumberOfResults>2</ojp:NumberOfResults>
					<ojp:IncludeTrackSections>true</ojp:IncludeTrackSections>
					<ojp:IncludeLegProjection>true</ojp:IncludeLegProjection>
					<ojp:IncludeTurnDescription>true</ojp:IncludeTurnDescription>
					<ojp:IncludeIntermediateStops>true</ojp:IncludeIntermediateStops>
				</ojp:Params>
			</ojp:OJPTripRequest>
		</ServiceRequest>
	</OJPRequest>
</OJP>

Now it seams to work correct.

**Comment by vasile** [comment]
Can't reproduce it with this response - https://gist.github.com/vasile/e601e8926075e1010b8e34a10aa5c727
`2 transfers` is shown for a multi-leg trip.
![image](https://user-images.githubusercontent.com/113994/127652719-731ee0a7-eabf-4b34-8b14-5494f0c05d4d.png)

@AndreasAtSBB please check again and if it doesn't work please reopen and attach the TripRequest response
