### ISSUE TITLE
sbb.ch shows more trains than ojp-js

### ISSUE THREAD

**Issue by iKK001** [openTdataCH/ojp-demo-app-src#124]
I observed that sbb.ch website shows more trains than the ojp-js library:

Esample: Lugano to Luzern from the SBB.ch website:

![sbb](https://github.com/openTdataCH/ojp-demo-app-src/assets/8404556/4f6d77df-3a28-48e8-80cc-0cf0c557ee6f)

Same tripRequest query with ojp-js library:

![Screenshot 2024-01-06 at 12 33 06](https://github.com/openTdataCH/ojp-demo-app-src/assets/8404556/ae20ce5e-e46f-40e4-9019-4d1a8b254517)

The 14:30 connection is clearly missing.

This can be repeated with many other connections...

Any idea why ??

------ 

After some more investigation, I observe that SBB.ch delivers connections wheras ojp-js - for certain cases - does not!

For example

Connection from "Chiasso" (id = 8505307) to "Basel, Holee" (id = 8589328)

Here what SBB.ch delivers...

![Screenshot 2024-01-06 at 18 05 09](https://github.com/openTdataCH/ojp-demo-app-src/assets/8404556/15c961c3-c736-4507-a441-29b29d36db78)

And here what ojp-js delivers (i.e. no trips !!!!!!...)

![Screenshot 2024-01-06 at 18 04 53](https://github.com/openTdataCH/ojp-demo-app-src/assets/8404556/70ef64ee-c657-4b24-b4f7-61326c56e541)

 Any idea why the difference ?

**Comment by vasile** [comment]
Was fixed in [Jan, 9](https://github.com/openTdataCH/ojp-demo-app-src/blob/main/CHANGELOG.md) release

**Comment by iKK001** [comment]
Thank you @vasile, great to hear. It is a wonderful work that you fulfill with this library. Thank you very much.
