### ISSUE TITLE
LocationName is required in TripRequest

### ISSUE THREAD

**Issue by u233336** [openTdataCH/ojp-demo-app-src#13]
LocationName has to be mentioned in the PlaceRef, otherwise the TR doesn't work properly:

<ojp:Origin>
     <ojp:PlaceRef>
         <ojp:LocationName>
             <ojp:Text>will_be_ignored</ojp:Text>
         </ojp:LocationName>
         <StopPointRef>8507000</StopPointRef>
     </ojp:PlaceRef>
	 <ojp:DepArrTime>2021-07-28T13:38:28</ojp:DepArrTime>
</ojp:Origin>

Same for the destination, doesn't have to be the "correct" location name because it will be ignored on the systems of Mentz.
Compare --> https://opentransportdata.swiss/en/cookbook/ojptriprequest/

**Comment by vasile** [comment]
It seems that also `RequestTimestamp` is now required in `<ServiceRequest>` and `ServiceRequest/ojp:OJPTripRequest` node, will add and populate them with the current timestamp.

**Comment by vasile** [comment]
It seems that also `<ojp:PlaceRef/ojp:GeoPosition` nodes need the LocationName. I've patched the SDK and published a new version, @u233336 please have a look.
![image](https://user-images.githubusercontent.com/113994/127558986-f14d24c1-467c-41f2-a359-ad45ab6f7460.png)

**Comment by u233336** [comment]
As mentioned in the email: the LIR doesn't work on TEST.
But maybe this is the wrong explanation for the issue "POI no longer visilble"

**Comment by vasile** [comment]
The LIR issues is addressed here
https://github.com/openTdataCH/ojp-demo-app-src/issues/9#issuecomment-889437221
