### ISSUE TITLE
TR DemoApp set NumberOfResults=0 for Monomodal Car

### ISSUE THREAD

**Issue by TO-mdv** [openTdataCH/ojp-demo-app-src#163]
Please change the parameters in the OJP Demo App for OJP2.0 for a monomodal CAR TripRequest.
Reason: if we try to make a monomodal car route, where no PT exists, we will always get an error. And if a user explicit choose "monomdol car", I gues he wants to see only the IV route and not PT route as well.

![Image](https://github.com/openTdataCH/ojp-demo-app-src/assets/72090402/cd522c54-8db3-4461-ab43-14e60386b026)

Currently, in the Request are the following parameters:
` 
          <NumberOfResultsAfter>5</NumberOfResultsAfter>
          <NumberOfResultsBefore>0</NumberOfResultsBefore>
`

For testing carFerry and TunnelTransport as well, the Parameters should better be:
`
                    <NumberOfResults>0</NumberOfResults>
  `

**Comment by vasile** [comment]
Closed - now the system sends 5 for public_transport and no `NumberOfResults` for the other modes
