### ISSUE TITLE
New Instance for Beta

### ISSUE THREAD

**Issue by AndreasAtSBB** [openTdataCH/ojp-demo-app-src#165]
Realis from Slovenia made a new OJP-System, which should be a new actieve OJP-System in the future.
The URL is: https://dev.simo.si/OpenAPI/LinkingAlpsBetaPhaseSBB/OJP
Can you add a new radio button in the Beta instance, that we may test it there?
Just for now all is like our PROD OJP-Service, so same configuration but the URL above.

**Comment by vasile** [comment]
Deployed to BETA
