### ISSUE TITLE
New BehiG Info Icon

### ISSUE THREAD

**Issue by AndreasAtSBB** [openTdataCH/ojp-demo-app-src#169]
We got new infos for the BehiG and Icon has changed, see description here:
https://www.oev-info.ch/de/datenmanagement/barrierefreier-zugang/behindertengleichstellung-im-oeffentlichen-verkehr

For stops where exiting was not possible we have the Info to call for a shuttle, see e.g. Stop Lorraine in Bern.
https://tools.odpch.ch/ojp-demo-v2/search?from=8590129&to=8588996&mode_types=monomodal&transport_modes=public_transport&trip_datetime=2024-10-21+15%3A36&stage=v2-prod
There we miss now the Icon:
![Image](https://github.com/user-attachments/assets/d853d165-a3d4-4c99-ae5e-4022204cab77)

The message in OJP is alraedy fixed/changed:
```
    <NameSuffix>
      <Text xml:lang="de">ALTERNATIVE_TRANSPORT</Text>
    </NameSuffix>
```

Can you change the Apps. (All versions) and probably also the SDK if required!

**Comment by AndreasAtSBB** [comment]
We got new infos for the BehiG and Icon has changed, see description here:
https://www.oev-info.ch/de/datenmanagement/barrierefreier-zugang/behindertengleichstellung-im-oeffentlichen-verkehr

For stops where exiting was not possible we have the Info to call for a shuttle, see e.g. Stop Lorraine in Bern.
https://tools.odpch.ch/ojp-demo-v2/search?from=8590129&to=8588996&mode_types=monomodal&transport_modes=public_transport&trip_datetime=2024-10-21+15%3A36&stage=v2-prod
There we miss now the Icon:
![Image](https://github.com/user-attachments/assets/d853d165-a3d4-4c99-ae5e-4022204cab77)

The message in OJP is alraedy fixed/changed:
                  <NameSuffix>
                    <Text xml:lang="de">ALTERNATIVE_TRANSPORT</Text>
                  </NameSuffix>

Can you change the Apps. (All versions) and probably also the SDK if required!

**Comment by AndreasAtSBB** [comment]
OJP 2.0 is now fine.
Link OJP 2.0 OK: https://tools.odpch.ch/ojp-demo-v2/search?from=8590129&to=8588996&mode_types=monomodal&transport_modes=public_transport&trip_datetime=2024-10-29+12%3A54&stage=v2-prod 
We need this one also on OJP 1.0
Not yet OK in OJP 1.0: https://opentdatach.github.io/ojp-demo-app/search?from=8590129&to=8588996&mode_types=monomodal&transport_modes=public_transport&trip_datetime=2024-10-29+12%3A54&stage=prod

**Comment by vasile** [comment]
@AndreasAtSBB on PROD (github pages) is not yet deployed, the Github automation bot is always closing this issue when the PR is merged :)

**Comment by vasile** [comment]
Deployed to PROD @AndreasAtSBB

**Comment by AndreasAtSBB** [comment]
Works fine now:
![Image](https://github.com/user-attachments/assets/897f142f-e9a4-4f2f-a716-8109fe03e958)
