### ISSUE TITLE
Sharing doesn't work anymore

### ISSUE THREAD

**Issue by AndreasAtSBB** [openTdataCH/ojp-demo-app-src#179]
With the newst app version the required part of the request is not generated.
With this search: https://tools.odpch.ch/ojp-demo-v2/search?from=46.767366%2C6.651634&to=46.729716%2C7.622367&mode_types=mode_at_start&transport_modes=bicycle_rental&trip_datetime=2024-11-12+09%3A13

There ist the extension tag, but not the reqired info in it:
```
        <Params>
          <NumberOfResults>5</NumberOfResults>
          <IncludeTrackSections>true</IncludeTrackSections>
          <IncludeLegProjection>true</IncludeLegProjection>
          <IncludeTurnDescription>true</IncludeTurnDescription>
          **_<Extension/>_**
          <UseRealtimeData>explanatory</UseRealtimeData>
        </Params>
```

Therefor the router will never give back something else than a PT-trip.

Detaild information about bulding the request are here:
https://opentransportdata.swiss/en/cookbook/ojptriprequest/#4_Intermodal_Trips_with_Public_Transport_and_eScooter_Bicycle_Rental_or_Car_Sharing_at_the_Beginning_andor_End

**Comment by vasile** [comment]
Deployed to PROD
