### ISSUE TITLE
Turn Description for first and last walk leg

### ISSUE THREAD

**Issue by ue71603** [openTdataCH/ojp-demo-app-src#21]
Why don't you show a Turn Description for the Walk legs at the beginning and at the end?

![image](https://user-images.githubusercontent.com/24227470/128498689-9de2e964-96f0-4551-ae82-732237e6fb91.png)

**Comment by vasile** [comment]
Assuming is [prod](https://opentdatach.github.io/ojp-demo-app/?from=46.967276%2C9.564735&to=46.835210%2C9.556242&mot_types=default&trip_datetime=2021-08-06+12%3A02&stage=prod) 

Response: https://gist.github.com/vasile/3eececa6b96fabf71453d86b0937cc81

Looks like a bug on the client, need to patch also the ContinuousLeg - marked as bug.

**Comment by vasile** [comment]
For Chur / Chur PostautoStation

show at least level / footpath as in the [response](https://gist.github.com/vasile/3eececa6b96fabf71453d86b0937cc81)

```
<ojp:PathLink>
    <ojp:Transition>level</ojp:Transition>
    <ojp:AccessFeatureType>footpath</ojp:AccessFeatureType>
</ojp:PathLink>
```

**Comment by vasile** [comment]
@u233336 @ue71603 - please check also for sharer / bike transfer if we have a response

**Comment by ue71603** [comment]
Self-Drive-Car
 https://opentdatach.github.io/ojp-demo-app/?from=46.972505%2C6.832668&to=46.994297%2C6.935128&mot_types=self-drive-car&trip_datetime=2021-08-06+14%3A39&stage=test

There are GuidanceAdvice:
                   <ojp:GuidanceAdvice>origin</ojp:GuidanceAdvice>
                    <ojp:TurnAction>left</ojp:TurnAction>

Sharing
https://opentdatach.github.io/ojp-demo-app/?from=46.965347%2C6.852451&to=46.994297%2C6.935128&mot_types=shared-mobility&trip_datetime=2021-08-06+14%3A39&stage=test

There is also GuidanceAdvice:
                      <ojp:Duration>PT0H1M24S</ojp:Duration>
                      <ojp:Length>94</ojp:Length>
                    </ojp:TrackSection>
                    <ojp:GuidanceAdvice>turn</ojp:GuidanceAdvice>
                    <ojp:TurnAction>left</ojp:TurnAction>
                  </ojp:PathGuidanceSection>

**Comment by ue71603** [comment]
always on test now

**Comment by AndreasAtSBB** [comment]
Actually there is no GUI element to show the turn descriptions (at least none that I know off). They are transmited, but not displayed.
For OJP 2.0 we try to fix this and improve the standard, in order that all possible turn actions can be shown (Some usual sentance are not yet possible).

**Comment by AndreasAtSBB** [comment]
Is OK for now, so we close.
