### ISSUE TITLE
Anpassen der P&R Labels

### ISSUE THREAD

**Issue by u233336** [openTdataCH/ojp-demo-app-src#23]
Since Mentz adapted the LIR (--> URL for P&R was added), the label of the P&R locations is some how strange: the name of the location ist missing, but instead "Link zur Webseite" is displayed:

![image](https://user-images.githubusercontent.com/74775157/137713572-7aa1b55f-1b6e-417d-9ea9-94162fe57e24.png)

**Comment by AndreasAtSBB** [comment]
Not needes anymore, because there are no more parking data in the platform.
