### ISSUE TITLE
Selector for PI 7 - making use of the new data

### ISSUE THREAD

**Issue by ue71603** [openTdataCH/ojp-demo-app-src#25]
![image](https://user-images.githubusercontent.com/24227470/139528595-07820f57-a946-4ac4-b6ee-7d39018bf8d0.png)

We have to move away from individual sharers.
We have the following types
* stops
* addresses
* parking
* sharing
* POI
I think we will have to have different symbols on the map for different "sharing types"
Necessary modes can be found here: https://github.com/VDVde/OJP/blob/master/OJP_ModesSupport.xsd

@u233336  : Can you think about the icons to use?
* own car
* shared car
* shared bike
* shared scooter/escooter
* bike
* taxi
* park&ride
* bike&ride
* car pooling

These should then show on the map.

**Comment by AndreasAtSBB** [comment]
Is obsolete by now. The new modes to use are described in other issues.
E.g. #51, #52, #53
