### ISSUE TITLE
Extend SDK with exchange point request

### ISSUE THREAD

**Issue by ue71603** [openTdataCH/ojp-demo-app-src#29]
The SDK should support EPR and MPTR as well.

EPR: Should work without and with Place.  There may be more than one way to get all exchange points.
The Paging must be supported. Important. Always use the ContineAt that was given in the previous answer (MENTZ does not have a continuous way of doing it otherwise)

E.g.
<?xml version="1.0" encoding="UTF-8"?>
<siri:OJP xmlns:siri="http://www.siri.org.uk/siri"
          xmlns:ojp="http://www.vdv.de/ojp"
          version="1.0">
    <siri:OJPRequest>
        <siri:ServiceRequest>
            <siri:RequestTimestamp>2021-04-21T15:20:35Z</siri:RequestTimestamp>
            <siri:RequestorRef>EFALocationCollector10.5.0.0-STR-DB-20</siri:RequestorRef>
            <siri:MessageIdentifier>A58C62B8-3E89-48F9-AECC-FD09CF155AE4</siri:MessageIdentifier>
            <ojp:OJPExchangePointsRequest>
                <siri:RequestTimestamp>2021-04-21T15:20:35Z</siri:RequestTimestamp>
                <ojp:Params>
                    <ojp:NumberOfResults>500</ojp:NumberOfResults>
                    <ojp:ContinueAt>0</ojp:ContinueAt>
                </ojp:Params>
            </ojp:OJPExchangePointsRequest>
        </siri:ServiceRequest>
    </siri:OJPRequest>
</siri:OJP>

It should also work for coordinates:
<?xml version="1.0" encoding="UTF-8"?>
<siri:OJP xmlns:siri="http://www.siri.org.uk/siri"
          xmlns:ojp="http://www.vdv.de/ojp"
          version="1.0">
    <siri:OJPRequest>
        <siri:ServiceRequest>
            <siri:RequestTimestamp>2021-04-21T15:20:35Z</siri:RequestTimestamp>
            <siri:RequestorRef>EFALocationCollector10.5.0.0-STR-DB-20</siri:RequestorRef>
            <siri:MessageIdentifier>A58C62B8-3E89-48F9-AECC-FD09CF155AE4</siri:MessageIdentifier>
            <ojp:OJPExchangePointsRequest>
                <siri:RequestTimestamp>2021-04-21T15:20:35Z</siri:RequestTimestamp>
                <ojp:PlaceRef>
                   <ojp:GeoPosition>
                     <Longitude>46.45</Longitude>
                     <Latitude>7.37</Latitude>                     
                   </ojp:GeoPosition>
                </ojp:PlaceRef>
                <ojp:Params>
                    <ojp:NumberOfResults>500</ojp:NumberOfResults>
                    <ojp:ContinueAt>0</ojp:ContinueAt>
                </ojp:Params>
            </ojp:OJPExchangePointsRequest>
        </siri:ServiceRequest>
    </siri:OJPRequest>
</siri:OJP>

and STopPlaceRef and StopPointRef

**Comment by ue71603** [comment]
should be done

**Comment by vasile** [comment]
Closing for now
