### ISSUE TITLE
Missing documentation (perhaps from slides)

### ISSUE THREAD

**Issue by ue71603** [openTdataCH/ojp-demo-app-src#32]
* Content of the folders
* installation guide
* modules that you used
* what you did with type script
* architecture of the angular part: What you generate how
* how to use the sdk
* Generelly there are way too few comments in the code (https://stackoverflow.com/questions/23072286/where-is-the-syntax-for-typescript-comments-documented)
* explain the config parts

**Comment by vasile** [comment]
Created https://github.com/openTdataCH/ojp-demo-app-src/blob/main/docs/README.md and sub-pages
