### ISSUE TITLE
Create OJP SDK package

### ISSUE THREAD

**Issue by vasile** [openTdataCH/ojp-demo-app-src#46]
Pack the [OJP SDK](https://github.com/openTdataCH/ojp-demo-app-src/tree/main/src/app/shared/ojp-sdk) into a stand-alone library (npm package?)

**Comment by ue71603** [comment]
I think this still would be a good idea.

**Comment by vasile** [comment]
Added 2 example apps in https://github.com/openTdataCH/ojp-js
