### ISSUE TITLE
SDK to include StopEventRequest and and additional iframe based "copy" of the functionality of the app time for coffee

### ISSUE THREAD

**Issue by ue71603** [openTdataCH/ojp-demo-app-src#49]
http://www.timeforcoffee.ch/

On phones it should use current location to show possible nearby stations.

**Comment by vasile** [comment]
Created PR - https://github.com/openTdataCH/ojp-demo-app-src/pull/60
Deployed to new [/board](https://opentdatach.github.io/ojp-demo-app/board) tab
