### ISSUE TITLE
New sharing type eScooter

### ISSUE THREAD

**Issue by AndreasAtSBB** [openTdataCH/ojp-demo-app-src#51]
Add the new category for sharing.
Best would be to arrange it in a group like Mentz, since there are 3 different sharing modes (bike, e-scooter, car).
![Grouping of menus for selecting tranport modes Screenshot 2022-06-07 161718](https://user-images.githubusercontent.com/85744651/173312656-fb60d325-6a70-4963-9410-6feff31885a7.png)
Picture is from a charging station example.

LIR Example for eScooter:
```
<ojp:OJPLocationInformationRequest>
    <RequestTimestamp>2022-02-23T08:24:38.345Z</RequestTimestamp>
    <MessageIdentifier>4711</MessageIdentifier>
    <ojp:InitialInput>
        <ojp:GeoRestriction>
            <ojp:Circle>
                <ojp:Center>
                    <Longitude>7.543</Longitude>
                    <Latitude>46.868</Latitude>
                </ojp:Center>
                <ojp:Radius>15000</ojp:Radius>
            </ojp:Circle>
        </ojp:GeoRestriction>
    </ojp:InitialInput>
    <ojp:Restrictions>
        <ojp:Type>poi</ojp:Type>
        <ojp:PointOfInterestFilter>
            <ojp:PointOfInterestCategory>
                <ojp:OsmTag>
                    <ojp:Tag>amenity</ojp:Tag>
                    <ojp:Value>escooter_rental</ojp:Value>
                </ojp:OsmTag>
            </ojp:PointOfInterestCategory>
        </ojp:PointOfInterestFilter>
    </ojp:Restrictions>
</ojp:OJPLocationInformationRequest>
```
Example for monomodal trip with eScooter:
... Origin ...  Destination ...
```
<ojp:Params>
    <ojp:NumberOfResults>3</ojp:NumberOfResults>
    <ojp:IncludeTrackSections>true</ojp:IncludeTrackSections>
    <ojp:IncludeLegProjection>true</ojp:IncludeLegProjection>
    <ojp:IncludeTurnDescription>true</ojp:IncludeTurnDescription>
    <ojp:IncludeIntermediateStops>true</ojp:IncludeIntermediateStops>
    <ojp:Extension>
        <ojp:ItModesToCover>escooter_rental</ojp:ItModesToCover>
    </ojp:Extension>
</ojp:Params>
```
Should be realised with a new selection in the mode option for the trip search.

eScooter at beginning:
```
<ojp:Extension>
    <ojp:Origin>
        <ojp:Mode>escooter_rental</ojp:Mode>
        <ojp:MaxDuration>PT30M</ojp:MaxDuration>
        <ojp:MinDuration>PT2M</ojp:MinDuration>
        <ojp:MaxDistance>20000</ojp:MaxDistance>
        <ojp:MinDistance>100</ojp:MinDistance>
    </ojp:Origin>
</ojp:Extension>
```

eScooter at end:
```
<ojp:Extension>
    <ojp:Destination>
        <ojp:Mode>escooter_rental</ojp:Mode>
        <ojp:MaxDuration>PT30M</ojp:MaxDuration>
        <ojp:MinDuration>PT2M</ojp:MinDuration>
        <ojp:MaxDistance>20000</ojp:MaxDistance>
        <ojp:MinDistance>100</ojp:MinDistance>
    </ojp:Destination>
</ojp:Extension>
```
How to solf the search in UI for the multimodal Trip is still to be defined/discussed.

General:
For the visualisation ofthe trip we may need to come up with some color patttern to separate same vehicle type but different kind of transport mode e.g. Public-Transport/Individual-Transport/Sharing(-Transport).  That way we can reuse the icon, but make clear what kind of transport it is. E.g for bike/cycle as owned cycle at beginning og a trip or a rental bike, which could be used at the end of a trip.

Escooter specific:
New icon need to be created. E.g. a scooter and and a electricity bolt sign.

**Comment by vasile** [comment]
Created #58
