### ISSUE TITLE
Showing multiple Charging Points of One Charging Station

### ISSUE THREAD

**Issue by u233336** [openTdataCH/ojp-demo-app-src#68]
One Charging Station can have one or more charging Points. 
e.g. the charging station 

<ojp:PointOfInterestCode>coord:833213:6067994:MRCV:Bern MOVE - Jupiterstrasse 41</ojp:PointOfInterestCode>

has 4 charging points.
We find these 4 charging points in the LIR, but on the map there is just one point.

**Comment by u233336** [comment]
![image](https://user-images.githubusercontent.com/74775157/199553287-44a20512-5059-4d4a-9bb9-4e3bed997eee.png)

<ojp:Code>1-1-1-CH*CCI*E21015</ojp:Code>
<ojp:Code>1-1-1-CH*CCI*E21016</ojp:Code>
<ojp:Code>1-1-1-CH*CCI*E21017</ojp:Code>
<ojp:Code>1-1-1-CH*CCI*E21018</ojp:Code>

**Comment by u233336** [comment]
[Dokumentation OJP - Ladestationen BFE-20221101_093456.pdf](https://github.com/openTdataCH/ojp-demo-app-src/files/9922662/Dokumentation.OJP.-.Ladestationen.BFE-20221101_093456.pdf)

**Comment by AndreasAtSBB** [comment]
On click the number of available/present charging stations should be visible. Somehow it should be made clear if the availability data is updated (on BFE page colored or grey icon).

**Comment by u233336** [comment]
Please add the information regarding availability

- AVAILABLE
- OCCUPIED
- ...

Visualisation of connector availability with colours. See also www.ichtankestrom.ch

**Comment by u233336** [comment]
![image](https://user-images.githubusercontent.com/74775157/216945364-764aa487-8e0d-4c97-b95c-b699a09b7162.png)

**Comment by u233336** [comment]
REQUEST
*******

<OJP xmlns="http://www.siri.org.uk/siri" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ojp="http://www.vdv.de/ojp" xsi:schemaLocation="http://www.siri.org.uk/siri ../ojp-xsd-v1.0/OJP.xsd" version="1.0">
  <OJPRequest>
    <ServiceRequest>
      <RequestorRef>OJP SDK v1.0</RequestorRef>
      <RequestTimestamp>2023-02-06T10:09:18.531Z</RequestTimestamp>
      <ojp:OJPLocationInformationRequest>
        <RequestTimestamp>2023-02-06T10:09:18.531Z</RequestTimestamp>
        <ojp:InitialInput>
          <ojp:GeoRestriction>
            <ojp:Rectangle>
              <ojp:UpperLeft>
                <Longitude>8.485019</Longitude>
                <Latitude>47.380917</Latitude>
              </ojp:UpperLeft>
              <ojp:LowerRight>
                <Longitude>8.494022</Longitude>
                <Latitude>47.376558</Latitude>
              </ojp:LowerRight>
            </ojp:Rectangle>
          </ojp:GeoRestriction>
        </ojp:InitialInput>
        <ojp:Restrictions>
          <ojp:NumberOfResults>300</ojp:NumberOfResults>
          <ojp:Type>poi</ojp:Type>
          <ojp:PointOfInterestFilter>
            <ojp:PointOfInterestCategory>
              <ojp:OsmTag>
                <ojp:Tag>amenity</ojp:Tag>
                <ojp:Value>charging_station</ojp:Value>
              </ojp:OsmTag>
            </ojp:PointOfInterestCategory>
          </ojp:PointOfInterestFilter>
        </ojp:Restrictions>
      </ojp:OJPLocationInformationRequest>
    </ServiceRequest>
  </OJPRequest>
</OJP>

RESPONSE
********

<siri:OJP xmlns:siri="http://www.siri.org.uk/siri" xmlns:ojp="http://www.vdv.de/ojp" version="1.0">
  <siri:OJPResponse>
    <siri:ServiceDelivery>
      <siri:ResponseTimestamp>2023-02-06T10:09:18Z</siri:ResponseTimestamp>
      <siri:ProducerRef>EFAController10.5.19.12-OJP-EFA02-P</siri:ProducerRef>
      <siri:Status>true</siri:Status>
      <ojp:OJPLocationInformationDelivery>
        <siri:ResponseTimestamp>2023-02-06T10:09:18Z</siri:ResponseTimestamp>
        <siri:Status>true</siri:Status>
        <ojp:CalcTime>5</ojp:CalcTime>
        <ojp:Location>
          <ojp:Location>
            <ojp:PointOfInterest>
              <ojp:PointOfInterestCode>coord:945001:5995786:MRCV:Zürich Freilager Zürich</ojp:PointOfInterestCode>
              <ojp:PointOfInterestName>
                <ojp:Text xml:lang="de">Freilager Zürich</ojp:Text>
              </ojp:PointOfInterestName>
              <ojp:PointOfInterestCategory>
                <ojp:OsmTag>
                  <ojp:Tag>amenity</ojp:Tag>
                  <ojp:Value>charging_station</ojp:Value>
                </ojp:OsmTag>
              </ojp:PointOfInterestCategory>
            </ojp:PointOfInterest>
            <ojp:LocationName>
              <ojp:Text xml:lang="de">Zürich</ojp:Text>
            </ojp:LocationName>
            <ojp:GeoPosition>
              <siri:Longitude>8.48909</siri:Longitude>
              <siri:Latitude>47.37934</siri:Latitude>
            </ojp:GeoPosition>
            <ojp:Attribute>
              <ojp:Text>
                <ojp:Text xml:lang="de">Freilager Zürich</ojp:Text>
              </ojp:Text>
              <ojp:Code>1-1-1-CH*SWIEE2601</ojp:Code>
            </ojp:Attribute>
            <ojp:Extension>
              <ojp:LocationExtensionStructure>
                <ojp:locationStatus>**AVAILABALE**</ojp:locationStatus>
              </ojp:LocationExtensionStructure>
            </ojp:Extension>
          </ojp:Location>
          <ojp:Complete>true</ojp:Complete>
          <ojp:Probability>1</ojp:Probability>
        </ojp:Location>
        <ojp:Location>
          <ojp:Location>
            <ojp:PointOfInterest>
              <ojp:PointOfInterestCode>coord:945001:5995786:MRCV:Zürich Freilager Zürich</ojp:PointOfInterestCode>
              <ojp:PointOfInterestName>
                <ojp:Text xml:lang="de">Freilager Zürich</ojp:Text>
              </ojp:PointOfInterestName>
              <ojp:PointOfInterestCategory>
                <ojp:OsmTag>
                  <ojp:Tag>amenity</ojp:Tag>
                  <ojp:Value>charging_station</ojp:Value>
                </ojp:OsmTag>
              </ojp:PointOfInterestCategory>
            </ojp:PointOfInterest>
            <ojp:LocationName>
              <ojp:Text xml:lang="de">Zürich</ojp:Text>
            </ojp:LocationName>
            <ojp:GeoPosition>
              <siri:Longitude>8.48909</siri:Longitude>
              <siri:Latitude>47.37934</siri:Latitude>
            </ojp:GeoPosition>
            <ojp:Attribute>
              <ojp:Text>
                <ojp:Text xml:lang="de">Freilager Zürich</ojp:Text>
              </ojp:Text>
              <ojp:Code>1-1-1-CH*SWIEE2548</ojp:Code>
            </ojp:Attribute>
            <ojp:Extension>
              <ojp:LocationExtensionStructure>
                <ojp:locationStatus>**AVAILABALE**</ojp:locationStatus>
              </ojp:LocationExtensionStructure>
            </ojp:Extension>
          </ojp:Location>
          <ojp:Complete>true</ojp:Complete>
          <ojp:Probability>1</ojp:Probability>
        </ojp:Location>
        <ojp:Location>
          <ojp:Location>
            <ojp:PointOfInterest>
              <ojp:PointOfInterestCode>coord:945001:5995786:MRCV:Zürich Freilager Zürich</ojp:PointOfInterestCode>
              <ojp:PointOfInterestName>
                <ojp:Text xml:lang="de">Freilager Zürich</ojp:Text>
              </ojp:PointOfInterestName>
              <ojp:PointOfInterestCategory>
                <ojp:OsmTag>
                  <ojp:Tag>amenity</ojp:Tag>
                  <ojp:Value>charging_station</ojp:Value>
                </ojp:OsmTag>
              </ojp:PointOfInterestCategory>
            </ojp:PointOfInterest>
            <ojp:LocationName>
              <ojp:Text xml:lang="de">Zürich</ojp:Text>
            </ojp:LocationName>
            <ojp:GeoPosition>
              <siri:Longitude>8.48909</siri:Longitude>
              <siri:Latitude>47.37934</siri:Latitude>
            </ojp:GeoPosition>
            <ojp:Attribute>
              <ojp:Text>
                <ojp:Text xml:lang="de">Freilager Zürich</ojp:Text>
              </ojp:Text>
              <ojp:Code>1-1-1-CH*SWIEE2600</ojp:Code>
            </ojp:Attribute>
            <ojp:Extension>
              <ojp:LocationExtensionStructure>
                <ojp:locationStatus>**OCCUPIED**</ojp:locationStatus>
              </ojp:LocationExtensionStructure>
            </ojp:Extension>
          </ojp:Location>
          <ojp:Complete>true</ojp:Complete>
          <ojp:Probability>1</ojp:Probability>
        </ojp:Location>
      </ojp:OJPLocationInformationDelivery>
    </siri:ServiceDelivery>
  </siri:OJPResponse>
</siri:OJP>

**Comment by u233336** [comment]
[ChargingStations_LIR.txt](https://github.com/openTdataCH/ojp-demo-app-src/files/10661933/ChargingStations_LIR.txt)
