### ISSUE TITLE
Add new stage: TEST LA

### ISSUE THREAD

**Issue by vasile** [openTdataCH/ojp-demo-app-src#8]
URL: https://odpch-test.cloud.tyk.io/la_test_active_server/

Authorization: Bearer 57c5dadd5e6307000100005e0e0520340d05419b8c1f13c17a20a8ab

**Comment by vasile** [comment]
Rolled it out on Github
![image](https://user-images.githubusercontent.com/113994/127615748-591539b4-16b5-4ffa-8ff4-2d7208ea4b40.png)

Currently the responses are broken (502 Gateway error) we're assuming it will be fixed soon (same request works on the other stages).

**Comment by vasile** [comment]
The 502 error is now handled and shown in #16 
![image](https://user-images.githubusercontent.com/113994/128258627-169c4486-e0aa-4542-b678-65dd313a0f67.png)

**Comment by vasile** [comment]
@AndreasAtSBB please provide me a working url (via permalink) so I can test this

**Comment by AndreasAtSBB** [comment]
I use this Url: https://odpch-test.cloud.tyk.io/la_test_active_server/

I didn't manage to get requests with GeoPosition to work, but in general it works. e.g.:
<?xml version="1.0" encoding="UTF-8"?>
<OJP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.siri.org.uk/siri" version="1.0" xmlns:ojp="http://www.vdv.de/ojp" xsi:schemaLocation="http://www.siri.org.uk/siri ../ojp-xsd-v1.0/OJP.xsd">
	<OJPRequest>
		<ServiceRequest>
			<RequestTimestamp>${=def now = new Date();now.format("yyyy-MM-dd'T'HH:mm:ss.SSSZ")}</RequestTimestamp>
			<RequestorRef>IRMA</RequestorRef>
			<ojp:OJPLocationInformationRequest>
				<RequestTimestamp>${=def now = new Date();now.format("yyyy-MM-dd'T'HH:mm:ss.SSSZ")}</RequestTimestamp>
				<MessageIdentifier>4711</MessageIdentifier>
				<ojp:PlaceRef>
					<ojp:LocationName>
						<ojp:Text>Zuerich HB</ojp:Text>
					</ojp:LocationName>
				</ojp:PlaceRef>
			</ojp:OJPLocationInformationRequest>
		</ServiceRequest>
	</OJPRequest>
</OJP>

TripRequest do only work with proper  StoppalceRef, which is limited matched with the pooled test server.

**Comment by AndreasAtSBB** [comment]
A sorry for the sripted time stamps. They work in SoapUI, otherwise you need to replace them with a proper time.

**Comment by AndreasAtSBB** [comment]
To make a full triprequest:
Fetch first the origin and destination ID:
Origin:
<?xml version="1.0" encoding="UTF-8"?>
<OJP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.siri.org.uk/siri" version="1.0" xmlns:ojp="http://www.vdv.de/ojp" xsi:schemaLocation="http://www.siri.org.uk/siri ../ojp-xsd-v1.0/OJP.xsd">
	<OJPRequest>
		<ServiceRequest>
			<RequestTimestamp>2021-07-14T14:38:22.976Z</RequestTimestamp>
			<RequestorRef>IRMA</RequestorRef>
			<ojp:OJPLocationInformationRequest>
				<RequestTimestamp>2021-07-14T14:38:22.976Z</RequestTimestamp>
				<MessageIdentifier>4711</MessageIdentifier>
				<ojp:PlaceRef>
					<ojp:LocationName>
						<ojp:Text>Zuerich HB</ojp:Text>
					</ojp:LocationName>
				</ojp:PlaceRef>
			</ojp:OJPLocationInformationRequest>
		</ServiceRequest>
	</OJPRequest>
</OJP>

Destination: 
<?xml version="1.0" encoding="UTF-8"?>
<OJP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.siri.org.uk/siri" version="1.0" xmlns:ojp="http://www.vdv.de/ojp" xsi:schemaLocation="http://www.siri.org.uk/siri ../ojp-xsd-v1.0/OJP.xsd">
	<OJPRequest>
		<ServiceRequest>
			<RequestTimestamp>2021-07-14T14:38:22.976Z</RequestTimestamp>
			<RequestorRef>IRMA</RequestorRef>
			<ojp:OJPLocationInformationRequest>
				<RequestTimestamp>2021-07-14T14:38:22.976Z</RequestTimestamp>
				<MessageIdentifier>4711</MessageIdentifier>
				<ojp:PlaceRef>
					<ojp:LocationName>
						<ojp:Text>Feldkirch</ojp:Text>
					</ojp:LocationName>
				</ojp:PlaceRef>
			</ojp:OJPLocationInformationRequest>
		</ServiceRequest>
	</OJPRequest>
</OJP>

Make the Trip Request:
<OJP xsi:schemaLocation="http://www.siri.org.uk/siri ../ojp-xsd-v1.0/OJP.xsd" version="1.0" xmlns="http://www.siri.org.uk/siri" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ojp="http://www.vdv.de/ojp">
	<OJPRequest>
		<ServiceRequest>
			<RequestTimestamp>2021-07-14T14:38:22.976Z</RequestTimestamp>
			<RequestorRef>OJP_SDK_v1.0</RequestorRef>
			<ojp:OJPTripRequest>
				<RequestTimestamp>2021-07-14T14:38:22.976Z</RequestTimestamp>
				<ojp:Origin>
					<ojp:PlaceRef>
						<ojp:StopPointRef>OJP:STOP:SBB:8503000|ZÃ¼rich HB@MRCV:950692:5995977</ojp:StopPointRef>
						<ojp:LocationName>
                       			<ojp:Text>x</ojp:Text>
                       		</ojp:LocationName>
					</ojp:PlaceRef>
					<ojp:DepArrTime>2021-07-14T14:38:22.976Z</ojp:DepArrTime>
				</ojp:Origin>
				<ojp:Destination>
					<ojp:PlaceRef>
						<ojp:StopPointRef>OJP:STOP:OBB:8101236|Feldkirch@MRCV:1069124:6018503</ojp:StopPointRef>
						<ojp:LocationName>
                       			<ojp:Text>x</ojp:Text>
                       		</ojp:LocationName>
					</ojp:PlaceRef>
				</ojp:Destination>
				<ojp:Params>
					<ojp:NumberOfResults>2</ojp:NumberOfResults>
					<ojp:IncludeTrackSections>true</ojp:IncludeTrackSections>
					<ojp:IncludeLegProjection>true</ojp:IncludeLegProjection>
					<ojp:IncludeTurnDescription>true</ojp:IncludeTurnDescription>
					<ojp:IncludeIntermediateStops>true</ojp:IncludeIntermediateStops>
				</ojp:Params>
			</ojp:OJPTripRequest>
		</ServiceRequest>
	</OJPRequest>
</OJP>
