### ISSUE TITLE
POI no longer visible

### ISSUE THREAD

**Issue by ue71603** [openTdataCH/ojp-demo-app-src#9]
Hi Vasile
When going to the demonstrator, switching to test and zooming in, I don't see the P&R and Bike sharers
https://opentdatach.github.io/ojp-demo-app/

![image](https://user-images.githubusercontent.com/24227470/126993470-839ceb3b-452c-4681-9522-7cc5cc08a868.png)

Es ist durchaus möglich, dass dies nicht bei Dir schiefläuft. Wir sollten allerdings irgendwo angeben können, dass hier Probleme bestehen. Allenfalls ein Log-Tab für solche Problem?

**Comment by vasile** [comment]
It seems that the POI request doesnt' work anymore, probably related with #13 
Lets have a look together on what params are required during our next sync.

**Comment by vasile** [comment]
Thanks @u233336 @ue71603 for the suggestions, the `LocationInformationReequest` should work again on TEST.
![image](https://user-images.githubusercontent.com/113994/127627538-b4b67e28-3fbe-4623-ba56-0c1ef2cc6cfd.png)

**Comment by vasile** [comment]
Error handling will be handled in #16
