### ISSUE TITLE
New Element "Topographic place" in "Toggle Map Layers" list 

### ISSUE THREAD

**Issue by AndreasAtSBB** [openTdataCH/ojp-demo-app-src#92]
Please add the new element "Topographic Place" between the "Stops" and the "Addresses".
So that the user can also see this on the map, because he can also choose it from the list, when searaching for places on the left side.

**Comment by AndreasAtSBB** [comment]
Removed the letter in front of elements in the map legend.

**Comment by vasile** [comment]
TODO: add some sample XML request of the current issue

**Comment by vasile** [comment]
Deployed to BETA, for now on there are no results for LIR + BBOX with `topographicPlace`

Example request: https://gist.github.com/vasile/39e96f2d503d37612095e78ade215b41
@u233336 , @TO-mdv
