### ISSUE TITLE
mark cancelled journey in the station board

### ISSUE THREAD

**Issue by u233336** [openTdataCH/ojp-demo-app-src#94]
in the station board we can see, that a train / bus / tram is late or on time, but we can't see the status "cancelled" although it is written in the StopEventResponse:

            <ojp:Service>
              <ojp:OperatingDayRef>2023-03-13</ojp:OperatingDayRef>
              <ojp:JourneyRef>ojp:91005:Y:R:j23:75:7308</ojp:JourneyRef>
              <siri:LineRef>ojp:91005:Y</siri:LineRef>
              <siri:DirectionRef>R</siri:DirectionRef>
              <ojp:Mode>
                <ojp:PtMode>rail</ojp:PtMode>
                <siri:RailSubmode>regionalRail</siri:RailSubmode>
                <ojp:Name>
                  <ojp:Text xml:lang="de">Zug</ojp:Text>
                </ojp:Name>
                <ojp:ShortName>
                  <ojp:Text xml:lang="de">R</ojp:Text>
                </ojp:ShortName>
              </ojp:Mode>
              <ojp:PublishedLineName>
                <ojp:Text xml:lang="de">R</ojp:Text>
              </ojp:PublishedLineName>
              <ojp:OperatorRef>ojp:11</ojp:OperatorRef>
              <ojp:OriginStopPointRef>8504304</ojp:OriginStopPointRef>
              <ojp:OriginText>
                <ojp:Text xml:lang="de">Sonceboz-Sombeval</ojp:Text>
              </ojp:OriginText>
              <ojp:DestinationStopPointRef>8500105</ojp:DestinationStopPointRef>
              <ojp:DestinationText>
                <ojp:Text xml:lang="de">Moutier</ojp:Text>
              </ojp:DestinationText>
              ### <ojp:Cancelled>true</ojp:Cancelled>
            </ojp:Service>

**Comment by u233336** [comment]
in the station board we can see, that a train / bus / tram is late or on time, but we can't see the status "cancelled" although it is written in the StopEventResponse:

            <ojp:Service>
              <ojp:OperatingDayRef>2023-03-13</ojp:OperatingDayRef>
              <ojp:JourneyRef>ojp:91005:Y:R:j23:75:7308</ojp:JourneyRef>
              <siri:LineRef>ojp:91005:Y</siri:LineRef>
              <siri:DirectionRef>R</siri:DirectionRef>
              <ojp:Mode>
                <ojp:PtMode>rail</ojp:PtMode>
                <siri:RailSubmode>regionalRail</siri:RailSubmode>
                <ojp:Name>
                  <ojp:Text xml:lang="de">Zug</ojp:Text>
                </ojp:Name>
                <ojp:ShortName>
                  <ojp:Text xml:lang="de">R</ojp:Text>
                </ojp:ShortName>
              </ojp:Mode>
              <ojp:PublishedLineName>
                <ojp:Text xml:lang="de">R</ojp:Text>
              </ojp:PublishedLineName>
              <ojp:OperatorRef>ojp:11</ojp:OperatorRef>
              <ojp:OriginStopPointRef>8504304</ojp:OriginStopPointRef>
              <ojp:OriginText>
                <ojp:Text xml:lang="de">Sonceboz-Sombeval</ojp:Text>
              </ojp:OriginText>
              <ojp:DestinationStopPointRef>8500105</ojp:DestinationStopPointRef>
              <ojp:DestinationText>
                <ojp:Text xml:lang="de">Moutier</ojp:Text>
              </ojp:DestinationText>
              ### <ojp:Cancelled>true</ojp:Cancelled>
            </ojp:Service>

**Comment by vasile** [comment]
Deployed to PROD, can be tested with a mock
https://opentdatach.github.io/ojp-demo-app/board?gist=3da967ad348d35b04f667921c9590b6d
